version: '3.9'

services:
  application.webapi:
    image: genocs/telegram_integration-webapi:1.0.4
    build:
      context: .
      dockerfile: webapi.dockerfile

  application.worker:
    image: genocs/telegram_integration-worker:1.0.4
    build:
      context: .
      dockerfile: worker.dockerfile
